name: Deploy and Test

on:
  push:
    branches: [main]

jobs:
  web-deploy:
    name: CI/CD -> Test and deploy
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: "http://api.sinduadihebat.my.id/"
    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: "7.4"
      - uses: actions/checkout@v2
      - name: FTP Deployment
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
